### PR TITLE
Bump to v0.5.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing #4, which got closed too quickly by the bot.

Closes #6, which got reopened after this one 🤦

### CODE REVIEW

**Comment by dirkgr** [comment]
I'm fine with releasing it as it is. In fact, it would be quite helpful for me if the version in conda-forge reproduces the problem on my machine.

**Comment by dirkgr** [comment]
Actually, do you want to test this patch? https://github.com/allenai/tango/pull/192

I looked at problems that people on the SqliteDict GitHub project reported, and this was one fix that worked for someone.

**Comment by dirkgr** [comment]
👀

**Comment by h-vetinari** [comment]
Great sleuthing! It worked! 🥳 🚀

**Comment by dirkgr** [comment]
Sweet! Psychic debugging strikes again!

**Pull request merged**
