### PR TITLE
Updated description of Tango

### PR DESCRIPTION
**Pull request by dirkgr**

### CODE REVIEW

**Comment by h-vetinari** [comment]
@dirkgr 
When you edit the readme directly, it will always get overwritten by the next "rerendering" of the feedstock. To persist changes, they need to be added to `meta.yaml`, which I did for you now. I had taken the summary from the github headline (upper right-hand corner on the main page of the repo), but I see this has changed now.

In any case, we have two different fields available - a shorter `summary:` and a longer `description:`, and I'm happy to populate these however you want! :)

**Comment by dirkgr** [comment]
The text that's there is the "short" summary. Here is the long description:

> AI2 Tango is a platform that allows you to build machine learning experiments out of steps that can be reused and repeated. It eliminates duplicate work, stores past results, and keeps track of how they were obtained so you can quickly identify and trace back your best work. Experiments are flexible, so you can change direction, pursue another idea and incorporate feedback, without losing previous results. Write your own steps by wrapping common Python functions, or take advantage of the library of pre-built steps for training models, working with datasets, and running evaluations. It is integrated with popular tools like the Huggingface transformers library, PyTorch Lightning, and others.

**Comment by h-vetinari** [comment]
@dirkgr, so this has both a summary and a description now, please let me know if you're fine with that and I'll merge...

**Comment by dirkgr** [comment]
I updated the summary. I hope it's not too long?

**Comment by h-vetinari** [comment]
Should be fine. And now the magic incantation (that anyone can do on a feedstock PR) to do the "rerendering" I was talking about:

@conda-forge-admin, please rerender

**Pull request merged**
